ktor:
  deployment:
    port: 8080
    shutdown:
      url: "/shutdown"
  application:
    modules:
      - com.slotspace.SerializationKt.configureSerialization
      - com.slotspace.di.NetworkModuleKt.networkModule
      - com.slotspace.RoutingKt.configureRouting
      - com.slotspace.MainKt.mainShutdown
